1.2 Numpy 라이브러리 임포트

In [1]:
import numpy as np # numpy 라이브러리를 임포트할 때, np로 별명을 지정해서 사용한다.

In [2]:
np.__version__

'1.19.2'

In [3]:
# 함수를 어떻게 사용했는지 기억이 안날 때, 
# 인터넷에 검색해서 사용방법을 알아낼 수 있지만, 
# help()를 이용해서 함수의 사용방법을 알 수 있다.

help(np.ndarray.dtype)

Help on getset descriptor numpy.ndarray.dtype:

dtype
    Data-type of the array's elements.
    
    Parameters
    ----------
    None
    
    Returns
    -------
    d : numpy dtype object
    
    See Also
    --------
    numpy.dtype
    
    Examples
    --------
    >>> x
    array([[0, 1],
           [2, 3]])
    >>> x.dtype
    dtype('int32')
    >>> type(x.dtype)
    <type 'numpy.dtype'>



1.3 Numpy의 배열, ndarray object

1.3.1 1D array 또는 (column)vector

In [5]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)

1.3.2 2D array 또는 matrix

In [6]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype = np.float32)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

1.3.3 3D array 또는 tensor

In [7]:
np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]], dtype = np.float32)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)

1.4 Numpy의 데이터 타입

In [8]:
np.int64 # Signed 64-bit integer types

numpy.int64

In [9]:
np.float32 # Standard double-percision floating point

numpy.float32

In [10]:
np.complex # Complex numbers represented by 128 floats

complex

In [11]:
np.bool # Boolean type storing TRUE and FALSE values

bool

In [12]:
np.object # Python object type

object

In [13]:
np.string_ # Fixed-length string type

numpy.bytes_

In [14]:
np.unicode_ #  Fixed-length unicode type

numpy.str_

1.5 placeholder를 이용해서 ndarray object 생성

1.5.1 zeros-vector(영벡터) 생성

In [15]:
np.zeros((3, 4), dtype = np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

1.5.2 ones-vector(일벡터) 생성

In [16]:
np.ones((3, 4), dtype = np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

1.5.3 np.arange(시작값, 끝값, 간격)

In [19]:
d = np.arange(10, 25, 5) # 끝값 전까지 표현
d

array([10, 15, 20])

In [20]:
d = np.arange(5, 40, 7)
d

array([ 5, 12, 19, 26, 33])

1.5.4 다른 배열과 같은 크기의 배열을 생성

In [18]:
tmp = np.arange(24).reshape((2, 3, 4))
np.zeros_like(tmp) # tmp 배열과 동일한 shape으로 0으로 채워진 배열 생성

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [22]:
np.ones_like(tmp)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

1.5.5 diagonal matrix(대각행렬) 생성

In [21]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

1.5.6 identity matrix(항등행렬) 생성

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1.5.7 균일한 간격으로 배열 생성

- 파이썬의 range와 비슷

In [24]:
np.arange(0, 15, 2, dtype = np.float32)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

1.5.8 균등한 간격으로 배열 생성

In [25]:
# linspace(start, stop, num)
np.linspace(0, 15, 9, dtype = np.float32) # (15-0)*(1/(9-1)), (15-0)*(2/(9-1)) ...

array([ 0.   ,  1.875,  3.75 ,  5.625,  7.5  ,  9.375, 11.25 , 13.125,
       15.   ], dtype=float32)

In [27]:
np.linspace(0, 15) # 50개까지 만들어짐
np.linspace(0, 15, 20) #20개까지 만들어짐

array([ 0.        ,  0.78947368,  1.57894737,  2.36842105,  3.15789474,
        3.94736842,  4.73684211,  5.52631579,  6.31578947,  7.10526316,
        7.89473684,  8.68421053,  9.47368421, 10.26315789, 11.05263158,
       11.84210526, 12.63157895, 13.42105263, 14.21052632, 15.        ])

1.5.9 지정된 상수값만을 가진 배열 생성

In [28]:
np.full((3, 4), 2, dtype = np.float32) # or np.ones((3, 4), dtype = np.float32 * 3)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)

1.5.10 무작위 값을 가지는 배열 생성

In [29]:
np.random.random((3, 4)) # [0, 1]범위에서 생성

array([[0.57546268, 0.03833145, 0.71875333, 0.46926145],
       [0.8935853 , 0.17496512, 0.28640005, 0.51395812],
       [0.20754055, 0.81088867, 0.87334642, 0.77575351]])

1.5.11 초기화되지 않은 배열 생성

In [30]:
np.empty((3, 4)) # 쓰레기 값이 들어가 있다.

array([[0.57546268, 0.03833145, 0.71875333, 0.46926145],
       [0.8935853 , 0.17496512, 0.28640005, 0.51395812],
       [0.20754055, 0.81088867, 0.87334642, 0.77575351]])

1.6 ndarray에 대한 기본적인 정보 조사하기

In [31]:
# 다음과 같은 배열이 있다고 가정한다.
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

1.6.1 배열의 shape를 확인

In [32]:
a.shape # 2*3*4 (depth, row, column)

(2, 3, 4)

1.6.2 배열의 길이(크기) 확인

In [33]:
len(a)

2

1.6.3 배열의 차원(dimension) 확인

In [34]:
a.ndim

3

1.6.4 배열의 요소(element) 개수를 확인

In [35]:
a.size

24

1.6.5 배열 요소의 데이터 타입 확인

In [36]:
a.dtype # Data Type of array elementx

dtype('int32')

1.6.6 배열 요소의 데이터 타입의 이름 확인

In [37]:
a.dtype.name

'int32'

1.6.7 배열 요소의 데이터 타입을 변경

In [39]:
# 원본 배열에 영향을 끼치지 않음
a.astype(np.bool) # 0 이하는 False, 0 초과는 True

array([[[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

1.7 Numpy 배열 연산

In [40]:
# 다음과 같은 Numpy 배열을 사용
a = np.random.random((3, 4))
b = np.arange(12, dtype = np.float32).reshape((3, 4))

a, b

(array([[0.40958612, 0.07486615, 0.39074681, 0.54291284],
        [0.74444735, 0.52795234, 0.22408203, 0.05001634],
        [0.7124122 , 0.39426805, 0.52816691, 0.23668663]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32))

1.7.1 사칙연산

In [41]:
# 더하기(+) 연산, elementwise 방식으로 동작
a + b # np.add(a, b)

array([[ 0.40958612,  1.07486615,  2.39074681,  3.54291284],
       [ 4.74444735,  5.52795234,  6.22408203,  7.05001634],
       [ 8.7124122 ,  9.39426805, 10.52816691, 11.23668663]])

In [42]:
# 빼기(-) 연산, elementwise 방식으로 동작
a - b # np.subtract(a, b)

array([[  0.40958612,  -0.92513385,  -1.60925319,  -2.45708716],
       [ -3.25555265,  -4.47204766,  -5.77591797,  -6.94998366],
       [ -7.2875878 ,  -8.60573195,  -9.47183309, -10.76331337]])

In [43]:
# 곱하기(*) 연산, elementwise 방식으로 동작
a * b #np.multiply(a, b)

array([[0.        , 0.07486615, 0.78149362, 1.62873851],
       [2.9777894 , 2.63976172, 1.34449218, 0.35011436],
       [5.69929758, 3.54841245, 5.28166907, 2.60355292]])

In [44]:
# 나누기(/) 연산, elementwise 방식으로 동작
a / b # np.divide(a, b)

<ipython-input-44-2c8b50ccadeb>:2: RuntimeWarning: divide by zero encountered in true_divide
  a / b # np.divide(a, b)


array([[       inf, 0.07486615, 0.19537341, 0.18097095],
       [0.18611184, 0.10559047, 0.037347  , 0.00714519],
       [0.08905152, 0.04380756, 0.05281669, 0.02151697]])

In [45]:
# 나머지(%) 연산, elementwise 방식으로 동작
a % b # np.remainder(a, b)

<ipython-input-45-d3f61206a80f>:2: RuntimeWarning: invalid value encountered in remainder
  a % b # np.remainder(a, b)


array([[       nan, 0.07486615, 0.39074681, 0.54291284],
       [0.74444735, 0.52795234, 0.22408203, 0.05001634],
       [0.7124122 , 0.39426805, 0.52816691, 0.23668663]])

1.7.2 기본적인 수학 관련 연산

1.7.2.1 지수함수

In [46]:
# 자연함수 e, 배열의 값이 지수함수(e^x)의 지수로 들어가서 연산이 이루어진다.
np.exp(b)

array([[1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01],
       [5.4598148e+01, 1.4841316e+02, 4.0342880e+02, 1.0966332e+03],
       [2.9809580e+03, 8.1030840e+03, 2.2026465e+04, 5.9874141e+04]],
      dtype=float32)

1.7.2.2 제곱근함수

In [47]:
np.sqrt(b)

array([[0.       , 1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898, 2.6457512],
       [2.828427 , 3.       , 3.1622777, 3.3166249]], dtype=float32)

1.7.2.3 사인함수

In [48]:
np.sin(a)

array([[0.39822972, 0.07479623, 0.38087904, 0.51663217],
       [0.67756546, 0.50376555, 0.22221144, 0.04999549],
       [0.65366119, 0.3841325 , 0.50395089, 0.23448292]])

1.7.2.4 코사인함수

In [50]:
np.cos(a)

array([[0.91728572, 0.99719884, 0.92462487, 0.85620745],
       [0.73546247, 0.86384042, 0.9749985 , 0.99874944],
       [0.75678732, 0.92327798, 0.86373231, 0.97212024]])

1.7.2.5 로그함수

In [51]:
np.log(a)

array([[-0.89260809, -2.59205347, -0.93969547, -0.61080649],
       [-0.29511315, -0.63874926, -1.49574309, -2.99540557],
       [-0.33909861, -0.93072427, -0.63834293, -1.44101825]])

1.7.2.6 내적계산

In [52]:
np.dot(a, b.T) # .T or tanspose() 는 (3, 4)를 (4, 3)로 만들어줌 (array 크기 변환)

array([[ 2.48509828,  8.15754594, 13.8299936 ],
       [ 1.12616542,  7.31215766, 13.49814991],
       [ 2.16066175,  9.64679689, 17.13293203]])

1.7.3 비교 연산

In [54]:
# 필터링 할 때 자주 사용, elementwise 방식으로 동작
a == b

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [55]:
a != b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
b > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
b < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [58]:
b <= 5

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

1.7.4 Aggregate Function(집계함수)

In [59]:
# b = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
b = np.arange(12, dtype = np.float32).reshape((3, 4))
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [60]:
# 디폴트로, 배열의 모든 요소를 더한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 요소를 더할 수 있다.
np.sum(b) # of b.sum()

66.0

In [61]:
# axis = 0, row 별로 요소를 더한다.
np.sum(b, axis = 0)

array([12., 15., 18., 21.], dtype=float32)

In [62]:
# axis = 1, column 별로 요소를 더한다.
np.sum(b, axis = 1)

array([ 6., 22., 38.], dtype=float32)

In [63]:
# 디폴트로, 배열의 요소 중 최솟값을 가져온다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 최솟값을 가져올 수 있다.
np.min(b) # b.min()

0.0

In [64]:
# axis = 0, row 별로 최솟값을 가져온다.
np.min(b, axis = 0)

array([0., 1., 2., 3.], dtype=float32)

In [65]:
# axis = 1, column 별로 최솟값을 가져온다.
np.min(b, axis = 1)

array([0., 4., 8.], dtype=float32)

In [66]:
# 디폴트로, 배열의 요소 중 최댓값을 가져온다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 최댓값을 가져올 수 있다.
np.max(b)

11.0

In [67]:
# 디폴트로, 배열의 요소 중 누적합계를 구한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 누적합계를 구할 수 있다.
np.cumsum(b)

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55., 66.],
      dtype=float32)

In [69]:
# 디폴트로, 배열의 요소 중 평균값을 구한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 평균값을 구할 수 있다.
np.mean(b)

5.5

In [70]:
# 디폴트로, 배열의 요소 중 중간값을 구한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 중간값을 구할 수 있다.
np.median(b)

5.5

In [71]:
# 디폴트로, 배열의 요소 중 표준편차를 구한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 표준편차 구할 수 있다.
np.std(b)

3.4520526

In [73]:
# 백분위수(percentile)를 이용해서, 1사분위수, ..., 4사분위수를 구할 수 있다.
# 4사분위수란? 전체 데이터 중 1/4 위치의 데이터를 뜻함
np.percentile(b, 0) # 최솟값

0.0

In [74]:
np.percentile(b, 50) # 2사분위수

5.5

In [75]:
np.percentile(b, 100) # 최댓값

11.0

1.8 Numpy의 Copy 3가지

In [77]:
c = np.arange(25, dtype = np.float32).reshape((5, 5))

# ndarray를 어떤 변수에 할당한다고 해보자.
tmp = c
tmp

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]], dtype=float32)

1.8.1 No Copy at All

In [78]:
tmp = c.view()
tmp

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]], dtype=float32)

In [79]:
print(tmp)
print(c)
print(id(tmp))
print(id(c))

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
2224368702208
2224368702128


In [80]:
id(tmp) == id(c)

False

1.8.2 Shadow Copy

In [81]:
tmp = c
tmp

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]], dtype=float32)

In [82]:
print(id(tmp))
print(id(c))

2224368702128
2224368702128


In [83]:
id(tmp) == id(c)

True

In [85]:
# 주소를 공유하고 있기 때문에
# tmp의 값을 변경하면, c의 값도 변경된다.
tmp[0][0] = -1

print('tmp : \n', tmp)
print('c : \n', c)

tmp : 
 [[-1.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
c : 
 [[-1.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


1.8.3 Deep Copy

- 원본 배열에 영향을 끼치지 않고 동일한 배열을 만들고 싶다면 deep copy를 해야 한다.

In [87]:
tmp = c.copy()
id(tmp) == id(c)

False

In [88]:
# 주소를 공유하고 있지 않기 때문에
# tmp의 값을 변경하더라도, b의 값은 변경되지 않는다.
tmp[0][0] = -9

print('tmp : \n', tmp)
print('c : \n', c)

tmp : 
 [[-9.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
c : 
 [[-1.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


1.9 Numpy의 슬라이싱, 인덱싱, 정렬

1.9.1 슬라이싱

In [89]:
# 파이썬의 List와 같은 슬라이싱을 제공한다.

d = np.arange(3)
d[0:2]

array([0, 1])

In [91]:
# 파이썬의 List와 다르게, 축(axis) 별로 슬라이싱이 가능하다.
# ','를 기준으로 슬라이싱을 하면 된다.

e = np.arange(9).reshape((3, 3))
e[0:2, :] # or e[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
e[:, 0:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [93]:
e[:, 2]

array([2, 5, 8])

In [94]:
# 행기준으로 뒤집고, 열기준으로 뒤집는 것도 가능하다.
e[::-1, ::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

1.9.2 boolean 인덱싱

In [95]:
# Numpy의 비교 연산을 이용해서 필터링을 할 수 있다.
f = np.arange(9).reshape((3, 3))
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
f[f < 4]

array([0, 1, 2, 3])

1.9.3 Fancy 인덱싱

In [97]:
# 슬라이싱을 사용해서 인덱싱을 하는 것 뿐만 아니라
# List와 ','를 이용해서 원하는 요소를 인덱싱할 수 있다.
# 그리고 앞에서 배운 boolean 인덱싱도 이용할 수 있다.
g = np.arange(12).reshape((3, 4))
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
# g의 두 번째 행, 첫 번째 행 전체 출력
g[[1, 0], :]

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [99]:
g[[2, 0], :2]

array([[8, 9],
       [0, 1]])

In [101]:
# g의 2, 4열의 요소만 추출
g[:, [False, True, False, True]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [102]:
g[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [104]:
# g에서 (1, 0), (0, 1), (1, 2), (0, 0)번째 요소를 추출
g[[1, 0, 1, 0], [0, 1, 2, 0]]

array([4, 1, 6, 0])

In [105]:
# g에서 첫 번째 행, 두 번째 행, 첫 번째 행, 두 번째 행을 선택하고 그렇게 만들어진 배열에 대해서
# 전체 행에 대해서 0, 1, 2, 0열의 요소로 인덱싱
g[[1, 0, 1, 0]][:, [0, 1, 2, 0]]

array([[4, 5, 6, 4],
       [0, 1, 2, 0],
       [4, 5, 6, 4],
       [0, 1, 2, 0]])

1.9.4 정렬

In [106]:
# 디폴트로, 마지막 축(여기서는 column을 기준으로)에 대해서 오름차순정렬한다.
# 'axis' 매개변수를 조절해서, row 별로 또는 column 별로 정렬할 수 있다.
h = np.random.random((3, 4))
h

array([[0.27478854, 0.44347732, 0.08848852, 0.4596471 ],
       [0.28598022, 0.56945737, 0.11965653, 0.10077093],
       [0.0352527 , 0.8389836 , 0.75671081, 0.7980321 ]])

In [107]:
# column 별로 오름차순정렬
np.sort(h)

array([[0.08848852, 0.27478854, 0.44347732, 0.4596471 ],
       [0.10077093, 0.11965653, 0.28598022, 0.56945737],
       [0.0352527 , 0.75671081, 0.7980321 , 0.8389836 ]])

In [108]:
# row 별로 오름차순정렬
np.sort(h, axis = 0)

array([[0.0352527 , 0.44347732, 0.08848852, 0.10077093],
       [0.27478854, 0.56945737, 0.11965653, 0.4596471 ],
       [0.28598022, 0.8389836 , 0.75671081, 0.7980321 ]])

In [109]:
np.sort(h, axis = 1)

array([[0.08848852, 0.27478854, 0.44347732, 0.4596471 ],
       [0.10077093, 0.11965653, 0.28598022, 0.56945737],
       [0.0352527 , 0.75671081, 0.7980321 , 0.8389836 ]])

In [110]:
# np.srot()는 정렬된 배열을 반환하지만, ndarray.sort()는 inplace 정렬이 일어난다.
h.sort()
h

array([[0.08848852, 0.27478854, 0.44347732, 0.4596471 ],
       [0.10077093, 0.11965653, 0.28598022, 0.56945737],
       [0.0352527 , 0.75671081, 0.7980321 , 0.8389836 ]])

1.10 Numpy 배열 조작

1.10.1 shape 조작하기

In [111]:
# reshape()를 통해서, 배열의 shape 모양을 바꾼다. (원본 배열을 바꾸지 않는다.)
tmp = np.arange(16)
tmp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [112]:
tmp.reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
tmp.reshape((2, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [114]:
# -1을 사용하면, 현재 주어진 정보를 토대로 나머지 부분을 채워준다.
tmp.reshape((8, -1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [115]:
tmp.reshape(2, 4, 2) # 배열의 크기가 맞아야 함

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [121]:
# ndarray.resize()를 통해서, 배열의 shape 모양을 바꾼다. (inplace 연산)
tmp = np.arange(15)

tmp.resize((3, 5))
tmp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
# 전치연산을 통해서, 행과 열의 위치를 변경할 수 있다.
tmp = np.arange(15).reshape((3, 5))
tmp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [123]:
np.transpose(tmp) # tmp.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [124]:
tmp.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

- ravel(), flatten()을 통해서, 다차원 배열을 1차원 배열로 변환
- ravel()은 shadow copy
- flatten()은 deep copy

In [125]:
tmp1 = np.arange(9).reshape((3, 3))
tmp2 = tmp1.ravel()

tmp1, tmp2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [126]:
tmp2[0] = -1
tmp1, tmp2

(array([[-1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]),
 array([-1,  1,  2,  3,  4,  5,  6,  7,  8]))

In [127]:
# flatten()의 경우
tmp1 = np.arange(9).reshape((3, 3))
tmp2 = tmp1.flatten()

tmp1, tmp2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [128]:
tmp2[0] = -1
tmp1, tmp2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([-1,  1,  2,  3,  4,  5,  6,  7,  8]))

1.10.2 배열에 값 넣기, 값 삭제하기

In [129]:
tmp1 = np.arange(9).reshape((3, 3))
tmp2 = np.arange(9).reshape((3, 3)) * 10
print(tmp1)
print("\n")
print(tmp2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [131]:
np.append(tmp1, tmp2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  0, 10, 20, 30, 40, 50, 60, 70,
       80])

In [132]:
np.append(tmp1, tmp2, axis = 0) # horizontal하게 값을 추가한다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [133]:
np.append(tmp1, tmp2, axis = 1) # vertical하게 값을 추가한다.

array([[ 0,  1,  2,  0, 10, 20],
       [ 3,  4,  5, 30, 40, 50],
       [ 6,  7,  8, 60, 70, 80]])

In [134]:
tmp = np.arange(6).reshape((2, 3))
tmp

array([[0, 1, 2],
       [3, 4, 5]])

In [135]:
np.insert(tmp, 1, -1)

array([ 0, -1,  1,  2,  3,  4,  5])

In [136]:
np.insert(tmp, 1, -1, axis = 0) # row를 기준으로 값을 집어넣는다.

array([[ 0,  1,  2],
       [-1, -1, -1],
       [ 3,  4,  5]])

In [137]:
np.delete(tmp, 1)

array([0, 2, 3, 4, 5])

In [138]:
tmp

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
np.delete(tmp, 1, axis = 1)

array([[0, 2],
       [3, 5]])

1.10.3 배열 결합하기

In [140]:
tmp1 = np.ones((5, 2))
tmp2 = np.zeros((3, 2))

# np.concatenate()는 'axis' 매개변수를 통해서 원하는 축에 두 배열을 연결할 수 있다.

np.concatenate([tmp1, tmp2]) # 두 배열을 위아래로 연결한다 ('axis = 0'이 디폴트로 설정되어있다.)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [142]:
tmp1 = np.ones((2, 5))
tmp2 = np.zeros((2, 3))

np.concatenate([tmp1, tmp2], axis = 1) # 두 배열을 좌우로 연결한다.

array([[1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.]])

In [141]:
tmp1 = np.ones((5, 2))
tmp2 = np.zeros((3, 2))

# np.vstack()은 두 배열을 위아래로 연결할 때 사용한다.

np.vstack([tmp1, tmp2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [143]:
tmp1 = np.ones((2, 5))
tmp2 = np.zeros((2, 3))

# np.hstack()은 두 배열을 좌우로 연결할 때 사용한다.

np.hstack([tmp1, tmp2])

array([[1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.]])

In [146]:
tmp1 = np.ones((2, 5))
tmp2 = np.zeros((2, 3))

# np.c_는 두 배열을 좌우로 연결할 때 사용한다.
# 인덱싱할 때 처럼, 대괄호를 사용해서 매서드를 호출한다.
np.c_[tmp1, tmp2]

array([[1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.]])

In [147]:
tmp1 = np.ones((5, 2))
tmp2 = np.zeros((3, 2))

# np.row_stack()은 두 배열을 위아래로 연결할 때 사용한다.
np.row_stack([tmp1, tmp2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [148]:
tmp1 = np.ones((2, 5))
tmp2 = np.zeros((2, 3))

# np.row_stack()은 두 배열을 좌우로 연결할 때 사용한다.
np.column_stack([tmp1, tmp2])

array([[1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.]])

1.10.4 배열 스플릿하기

In [149]:
tmp = np.arange(3)
tmp

array([0, 1, 2])

In [150]:
# np.hsplit()은 좌우로(column-wire) 배열을 스플릿할 때 사용한다.
np.hsplit(tmp,3)

[array([0]), array([1]), array([2])]

In [151]:
tmp = np.arange(12).reshape(2, 2, 3)
tmp

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [152]:
# np.vsplit()은 위아래로(row-wise) 배열을 스플릿할 때 사용한다.
np.vsplit(tmp, 2)

[array([[[0, 1, 2],
         [3, 4, 5]]]),
 array([[[ 6,  7,  8],
         [ 9, 10, 11]]])]